services:
  loja_seu_manoel:
    image: ${DOCKER_REGISTRY-}lojaseumanoel
    build:
      context: .
      dockerfile: Loja_Seu_Manoel/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: "12345@seu_manoel"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./criaDB.sql:/docker-entrypoint-initdb.d/criaDB.sql
    expose:
         - '1433'
volumes:
  sqlserverdata: